[package]
name = "nbac"
version = "0.20260731.1"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = { version = "4.6", features = ["unstable-dynamic"] }
anyhow = "1"
console = "0.16"
serde = { version = "1", features = ["derive"] }
toml = "1"
serde_json = "1.0.151"
thiserror = "2.0.19"
rustix = { version = "1.1.4", features = ["fs", "process"] }
sha2 = "0.11.0"
