auto-allocate-uids = true
build-users-group =
experimental-features = nix-command auto-allocate-uids cgroups flakes pipe-operators
extra-system-features = uid-range
use-cgroups = true
max-jobs = auto
